name: "Twisted Metal: Harbor City"
sha1: 59695de214d38d1c0af9167412271fe2a446a13a
options:
  basename: TMHC
  target_path: config/TMHC.ELF
  base_path: ../
  compiler: GCC
  find_file_boundaries: False
  platform: ps2
  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  symbol_addrs_path: config/symbol_addrs.txt
  nonmatchings_path: nonmatchings
  ld_script_path: TMHC.ld
  asm_path: asm
  src_path: src
  build_path: build
  section_order: [".text", ".data", ".rodata", ".bss"]
  auto_all_sections: [".data", ".rodata", ".bss"]
  disasm_unknown: True
  named_regs_for_c_funcs: False
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x1000
    vram: 0x2100000
    bss_size: 0x3fbcf8
    subalign: 1
    align: 4
    subsegments:
      # .text
      - [0x1000, asm, sdk/crt0]

      - [0x1280, asm, tmhc/action_mgr]
      - [0x1930, asm, tmhc/action_context]
      - [0x19c8, asm, tmhc/action]
      - [0x1fc0, asm, tmhc/car_ai]
      - [0xca80, asm, tmhc/breadcrumbs]
      - [0xcbf8, asm, tmhc/ai_char_round_robin]
      - [0xcc10, asm, tmhc/ai_char]
      - [0x10f08, asm, tmhc/ai_char_anim]
      - [0x110e8, asm, tmhc/ai_anim_aim_at]
      - [0x11348, asm, tmhc/ai_char_attract_pts]
      - [0x164e8, asm, tmhc/ai_char_baton_guard]
      - [0x168c0, asm, tmhc/ai_char_brain]
      - [0x177e0, asm, tmhc/ai_char_brain_state]
      - [0x17ca8, asm, tmhc/ai_char_brain_idle]
      - [0x17fc0, asm, tmhc/ai_char_brain_alert]
      - [0x18090, asm, tmhc/ai_char_brain_mull_around]
      - [0x183e0, asm, tmhc/ai_char_brain_patrol]
      - [0x18698, asm, tmhc/ai_char_brain_engage_hand_to_hand]
      - [0x18b20, asm, tmhc/ai_char_brain_engage_baton]
      - [0x19108, asm, tmhc/ai_char_brain_engage_to_shoot]
      - [0x19450, asm, tmhc/ai_char_brain_shoot]
      - [0x19768, asm, tmhc/ai_char_engage_cattle_prod]
      - [0x19e48, asm, tmhc/ai_char_brain_dead]
      - [0x19f88, asm, tmhc/ai_char_brain_take_hit]
      - [0x1a1a8, asm, tmhc/ai_char_brain_take_shove]
      - [0x1a3f0, asm, tmhc/ai_char_brain_take_car_hit]
      - [0x1a928, asm, tmhc/ai_char_brain_tumble]
      - [0x1ab30, asm, tmhc/ai_char_brain_seek_using_path]
      - [0x1add0, asm, tmhc/ai_char_brain_dive_out_of_way]
      - [0x1b038, asm, tmhc/ai_char_brain_run_out_of_way]
      - [0x1b2a0, asm, tmhc/ai_char_brain_walk_out_of_way]
      - [0x1b508, asm, tmhc/ai_char_cattle_prod_guard]
      - [0x1b8e0, asm, tmhc/ai_char_collis]
      - [0x1cca8, asm, tmhc/ai_char_dyn]
      - [0x1ced0, asm, tmhc/ai_mgr_round_robin]
      - [0x1cf20, asm, tmhc/ai_char_manager]
      - [0x1e7d0, asm, tmhc/timer_bar]
      - [0x1ea00, asm, tmhc/ai_char_nav]
      - [0x20ab8, asm, tmhc/ai_char_p_tool]
      - [0x22b70, asm, tmhc/ai_char_shotgun_guard]
      - [0x22f40, asm, tmhc/ai_char_state]
      - [0x23060, asm, tmhc/ai_char_state_idle]
      - [0x23298, asm, tmhc/ai_char_state_idle_ready]
      - [0x23608, asm, tmhc/ai_char_state_idle_battle_stance]
      - [0x23840, asm, tmhc/ai_char_state_dive]
      - [0x23b00, asm, tmhc/ai_char_state_run]
      - [0x23f70, asm, tmhc/ai_char_state_walk]
      - [0x24148, asm, tmhc/ai_char_state_attack_baton]
      - [0x24410, asm, tmhc/ai_char_state_attack_cattle_prod]
      - [0x246d8, asm, tmhc/ai_char_state_shield_block]
      - [0x24998, asm, tmhc/ai_char_state_fire]
      - [0x24a90, asm, tmhc/ai_char_state_death]
      - [0x24ca0, asm, tmhc/ai_char_state_alert]
      - [0x24da8, asm, tmhc/ai_char_state_take_hit]
      - [0x24f38, asm, tmhc/ai_char_state_take_car_hit]
      - [0x24fd0, asm, tmhc/ai_char_state_tumble]
      - [0x25038, asm, tmhc/ai_char_state_take_shove]
      - [0x25398, asm, tmhc/ai_char_state_throw]
      - [0x25438, asm, tmhc/ai_char_state_stand_aim]
      - [0x25670, asm, tmhc/ai_char_state_stand_shoot]
      - [0x258a8, asm, tmhc/ai_char_generic_ped]
      - [0x25dc8, asm, tmhc/ai_ped_p_tool]
      - [0x26ad8, asm, tmhc/ai_path_finder]
      - [0x27b70, asm, tmhc/ai_point_nav]
      - [0x28178, asm, tmhc/ai_p_tool]
      - [0x2dff8, asm, tmhc/ai_global_p_tool]
      - [0x30598, asm, tmhc/anim_sound]
      - [0x30b28, asm, tmhc/hud_anim_sound]
      - [0x30bb8, asm, tmhc/anim_trigger]
      - [0x30e40, asm, tmhc/attract_mode_mgr]
      - [0x310e0, asm, tmhc/attract_script]
      - [0x31530, asm, tmhc/persist_auto_save]
      - [0x315d0, asm, tmhc/auto_save_start]
      - [0x31818, asm, tmhc/first_auto_save]
      - [0x31db0, asm, tmhc/auto_save_disable_menu]
      - [0x32168, asm, tmhc/avatar]
      - [0x32228, asm, tmhc/camera_data]
      - [0x32318, asm, tmhc/avatar_volumes]
      - [0x32930, asm, tmhc/axel_special_weap]
      - [0x33788, asm, tmhc/bullet_casing]
      - [0x33e40, asm, tmhc/bullet_casings]
      - [0x342e0, asm, tmhc/burning_man]
      - [0x34ec8, asm, tmhc/burning_men]
      - [0x350e0, asm, tmhc/cameras]
      - [0x35558, asm, tmhc/camera]
      - [0x358e8, asm, tmhc/car]
      - [0x3d1b8, asm, tmhc/car_anim]
      - [0x3dff8, asm, tmhc/car_camera]
      - [0x40258, asm, tmhc/car_control]
      - [0x42960, asm, tmhc/car_destruct]
      - [0x42ba0, asm, tmhc/car_dead_hull]
      - [0x43dd8, asm, tmhc/car_dyn]
      - [0x4d3a0, asm, tmhc/car_hud_main_element]
      - [0x4d400, asm, tmhc/car_hud_radar_element]
      - [0x4dbd8, asm, tmhc/car_hud_online_lower_left_score_element]
      - [0x4dd80, asm, tmhc/car_hud_online_lower_center_score_element]
      - [0x4deb0, asm, tmhc/car_hud_online_upper_right_score_element]
      - [0x4dfd0, asm, tmhc/car_hud_car_indicators_element]
      # TODO: Why are there two of these?
      - [0x4fd08, asm, tmhc/car_hud_radar_element_2]
      - [0x511d8, asm, tmhc/car_hud_health_element]
      - [0x518d0, asm, tmhc/car_hud_energy_element]
      - [0x51bd0, asm, tmhc/car_hud_message_element]
      - [0x52000, asm, tmhc/car_hud_gun_charge_element]
      - [0x521b0, asm, tmhc/car_hud_weapon_select_element]
      - [0x52ad0, asm, tmhc/car_hud_debug_controller_element]
      - [0x52b18, asm, tmhc/car_hud]
      - [0x53420, asm, tmhc/car_mgr]
      - [0x568e8, asm, tmhc/car_mode]
      - [0x56ef0, asm, tmhc/car_pager]
      - [0x58340, asm, tmhc/car_pager_task]
      - [0x58918, asm, tmhc/car_script]
      - [0x589e8, asm, tmhc/car_hud_sound]
      - [0x58d60, asm, tmhc/fodder_car_sound]
      - [0x59160, asm, tmhc/car_weap_anim_sound]
      - [0x595b0, asm, tmhc/car_sound]
      - [0x5c628, asm, tmhc/car_targeting]
      - [0x5c9a0, asm, tmhc/car_weap]
      - [0x5dad8, asm, tmhc/car_weap_bay]
      - [0x5dce8, asm, tmhc/car_weap_set]
      - [0x5e958, asm, tmhc/car_machine_guns]
      - [0x5f3e0, asm, tmhc/car_missiles]
      - [0x5f860, asm, tmhc/car_gas_can]
      - [0x5fde0, asm, tmhc/car_drop_mine]
      - [0x60180, asm, tmhc/car_flak]
      - [0x60c50, asm, tmhc/car_env_weap]
      - [0x610b8, asm, tmhc/car_freeze_missiles]
      - [0x61410, asm, tmhc/car_swarmer_missiles]
      - [0x61ce0, asm, tmhc/car_weap_sound]
      - [0x62458, asm, tmhc/weapon_sound]
      - [0x634a0, asm, tmhc/char]
      - [0x65050, asm, tmhc/char_anim]
      - [0x65298, asm, tmhc/anim_look_at]
      - [0x656f0, asm, tmhc/char_camera]
      - [0x66750, asm, tmhc/char_collis]
      - [0x67bb8, asm, tmhc/char_control]
      - [0x68b08, asm, tmhc/char_dyn]
      - [0x69c78, asm, tmhc/char_hud_main_element]
      - [0x69cd8, asm, tmhc/char_hud_radar_element]
      - [0x6a228, asm, tmhc/char_hud_car_indicators_element]
      # TODO: What is going on with the duplicates?
      - [0x6ac10, asm, tmhc/char_hud_radar_element_2]
      - [0x6b598, asm, tmhc/char_hud_health_element]
      - [0x6bc58, asm, tmhc/char_hud_stamina_element]
      - [0x6bf98, asm, tmhc/char_hud_mash_element]
      - [0x6c468, asm, tmhc/char_hud_message_element]
      - [0x6c898, asm, tmhc/char_hud_weapon_select_element]
      - [0x6c8f8, asm, tmhc/char_hud]
      - [0x6cbc0, asm, tmhc/char_mode]
      - [0x6d610, asm, tmhc/char_pickup]
      - [0x6e498, asm, tmhc/char_reset]
      - [0x6f080, asm, tmhc/char_state]
      - [0x6f390, asm, tmhc/char_state_idle]
      - [0x6fbe0, asm, tmhc/char_state_run]
      - [0x70bf0, asm, tmhc/char_state_jump]
      - [0x717f0, asm, tmhc/char_state_climb]
      - [0x73180, asm, tmhc/char_state_dodge_roll]
      - [0x739f8, asm, tmhc/char_state_shove]
      - [0x73d30, asm, tmhc/char_state_death]
      - [0x73fd8, asm, tmhc/char_state_punch]
      - [0x749a8, asm, tmhc/char_state_bat_swipe]
      - [0x75330, asm, tmhc/char_state_block]
      - [0x75728, asm, tmhc/char_state_throw]
      - [0x75a38, asm, tmhc/char_state_pickup]
      - [0x75cf0, asm, tmhc/char_state_pickup_miss]
      - [0x75f30, asm, tmhc/char_state_knock_back]
      - [0x76340, asm, tmhc/char_state_ledge_grab]
      - [0x77550, asm, tmhc/char_state_ledge_wobble]
      - [0x77c40, asm, tmhc/char_state_mantle]
      - [0x78638, asm, tmhc/char_targeting]
      - [0x78988, asm, tmhc/char_tweaks]
      - [0x7ab38, asm, tmhc/char_camera_tweaks]
      - [0x7b0b8, asm, tmhc/char_weap]
      - [0x7b398, asm, tmhc/char_weap_set]
      - [0x7b730, asm, tmhc/char_machine_gun]
      - [0x7bfb8, asm, tmhc/chunk_map]
      - [0x7c6f8, asm, tmhc/chunk_script]
      - [0x7da78, asm, tmhc/artifact]
      - [0x7ebe8, asm, tmhc/collector]
      - [0x80880, asm, tmhc/debris]

      - [0x299c10, databin] # .vutext
      - [0x2a6d00, databin] # .data
      - [0x2c8e00, databin] # .rodata
      - [0x32bf00, databin] # .gcc_except_table
      - [0x32c080, databin] # .sdata
      # - [0xb54, sbss] # .sbss
      - [0x32f6d4, databin] # .reginfo
      - [0x3330b4, databin] # .DVP.overlay
      - [0x338aec, databin] # .debug_str
      - [0x339b38, databin] # .stab
      - [0x353644, databin] # .stabstr
      - [0x353774, databin] # .mdebug
      - [0x3fbcf8, databin] # .bss
      - [0x445360, databin] # .symtab
      - [0x48c420, databin] # .strtab
      - [0x4f670b, databin] # .shstrtab
  - [0x4f71b4]
