name: "Twisted Metal: Harbor City"
sha1: 59695de214d38d1c0af9167412271fe2a446a13a
options:
  basename: TMHC
  target_path: config/TMHC.ELF
  base_path: ../
  compiler: GCC
  find_file_boundaries: False
  platform: ps2
  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto.txt
  symbol_addrs_path: config/symbol_addrs.txt
  nonmatchings_path: nonmatchings
  ld_script_path: TMHC.ld
  asm_path: asm
  src_path: src
  build_path: build
  section_order: [".text", ".data", ".rodata", ".bss"]
  auto_all_sections: [".data", ".rodata", ".bss"]
  disasm_unknown: True
  named_regs_for_c_funcs: False
segments:
  - [0, databin, elf_header]
  - name: main
    type: code
    start: 0x1000
    vram: 0x2100000
    bss_size: 0x3fbcf8
    subalign: 1
    align: 4
    subsegments:
      # .text
      - [0x1000, asm, sdk/crt0]

      - [0x1280, asm, tmhc/actionmgr]
      - [0x1930, asm, tmhc/actioncontext]
      - [0x19c8, asm, tmhc/action]
      - [0x1fc0, asm, tmhc/carai]
      - [0xca80, asm, tmhc/breadcrumbs]
      - [0xcbf8, asm, tmhc/aicharroundrobin]
      - [0xcc10, asm, tmhc/aichar]
      - [0x10f08, asm, tmhc/aicharanim]
      - [0x110e8, asm, tmhc/aianimaimat]
      - [0x11348, asm, tmhc/aicharattractpts]
      - [0x164e8, asm, tmhc/aicharbatonguard]
      - [0x168c0, asm, tmhc/aicharbrain]
      - [0x177e0, asm, tmhc/aicharbrainstate]
      - [0x17ca8, asm, tmhc/aicharbrainidle]
      - [0x17fc0, asm, tmhc/aicharbrainalert]
      - [0x18090, asm, tmhc/aicharbrainmullaround]
      - [0x183e0, asm, tmhc/aicharbrainpatrol]
      - [0x18698, asm, tmhc/aicharbrainengagehandtohand]
      - [0x18b20, asm, tmhc/aicharbrainengagebaton]
      - [0x19108, asm, tmhc/aicharbrainengagetoshoot]
      - [0x19450, asm, tmhc/aicharbrainshoot]
      - [0x19768, asm, tmhc/aicharengagecattleprod]
      - [0x19e48, asm, tmhc/aicharbraindead]
      - [0x19f88, asm, tmhc/aicharbraintakehit]
      - [0x1a1a8, asm, tmhc/aicharbraintakeshove]
      - [0x1a3f0, asm, tmhc/aicharbraintakecarhit]
      - [0x1a928, asm, tmhc/aicharbraintumble]
      - [0x1ab30, asm, tmhc/aicharbrainseekusingpath]
      - [0x1add0, asm, tmhc/aicharbraindiveoutofway]
      - [0x1b038, asm, tmhc/aicharbrainrunoutofway]
      - [0x1b2a0, asm, tmhc/aicharbrainwalkoutofway]
      - [0x1b508, asm, tmhc/aicharcattleprodguard]
      - [0x1b8e0, asm, tmhc/aicharcollis]
      - [0x1cca8, asm, tmhc/aichardyn]
      - [0x1ced0, asm, tmhc/aimgrroundrobin]
      - [0x1cf20, asm, tmhc/aicharmanager]
      - [0x1e7d0, asm, tmhc/tierbr]
      - [0x1ea00, asm, tmhc/aicharnav]
      - [0x20ab8, asm, tmhc/aicharptool]
      - [0x22b70, asm, tmhc/aicharshotgunguard]
      - [0x22f40, asm, tmhc/aicharstate]
      - [0x23060, asm, tmhc/aicharstateidle]
      - [0x23298, asm, tmhc/aicharstateidleready]
      - [0x23608, asm, tmhc/aicharstateidlebattlestance]
      - [0x23840, asm, tmhc/aicharstatedive]
      - [0x23b00, asm, tmhc/aicharstaterun]
      - [0x23f70, asm, tmhc/aicharstatewalk]
      - [0x24148, asm, tmhc/aicharstateattackbaton]
      - [0x24410, asm, tmhc/aicharstateattackcattleprod]
      - [0x246d8, asm, tmhc/aicharstateshieldblock]
      - [0x24998, asm, tmhc/aicharstatefire]
      - [0x24a90, asm, tmhc/aicharstatedeath]
      - [0x24ca0, asm, tmhc/aicharstatealert]
      - [0x24da8, asm, tmhc/aicharstatetakehit]
      - [0x24f38, asm, tmhc/aicharstatetakecarhit]
      - [0x24fd0, asm, tmhc/aicharstatetumble]
      - [0x25038, asm, tmhc/aicharstatetakeshove]
      - [0x25398, asm, tmhc/aicharstatethrow]
      - [0x25438, asm, tmhc/aicharstatestandaim]
      - [0x25670, asm, tmhc/aicharstatestandshoot]
      - [0x258a8, asm, tmhc/aichargenericped]
      - [0x25dc8, asm, tmhc/aipedptool]
      - [0x26ad8, asm, tmhc/aipathfinder]
      - [0x27b70, asm, tmhc/aipointnav]
      - [0x28178, asm, tmhc/aiptool]
      - [0x2dff8, asm, tmhc/aiglobalptool]
      - [0x30598, asm, tmhc/animsound]
      - [0x30b28, asm, tmhc/hudanimsound]
      - [0x30bb8, asm, tmhc/animtrigger]
      - [0x30e40, asm, tmhc/attractmodemgr]
      - [0x310e0, asm, tmhc/attractscript]
      - [0x31530, asm, tmhc/persistautosave]
      - [0x315d0, asm, tmhc/autosavestart]
      - [0x31818, asm, tmhc/firstautosave]
      - [0x31db0, asm, tmhc/autosavedisablemenu]
      - [0x32168, asm, tmhc/avatar]
      - [0x32228, asm, tmhc/cameradata]
      - [0x32318, asm, tmhc/avatarvolumes]
      - [0x32930, asm, tmhc/axelspecialweap]
      - [0x33788, asm, tmhc/bulletcasing]
      - [0x33e40, asm, tmhc/bulletcasings]
      - [0x342e0, asm, tmhc/burningman]
      - [0x34ec8, asm, tmhc/burningmen]
      - [0x350e0, asm, tmhc/cameras]
      - [0x35558, asm, tmhc/camera]
      - [0x358e8, asm, tmhc/car]
      - [0x3d1b8, asm, tmhc/caranim]
      - [0x3dff8, asm, tmhc/carcamera]
      - [0x40258, asm, tmhc/carcontrol]
      - [0x42960, asm, tmhc/cardestruct]
      - [0x42ba0, asm, tmhc/cardeadhull]
      - [0x43dd8, asm, tmhc/cardyn]
      - [0x4d3a0, asm, tmhc/carhud]
      - [0x53420, asm, tmhc/carmgr]
      - [0x568e8, asm, tmhc/carmode]
      - [0x56ef0, asm, tmhc/carpager]
      - [0x58340, asm, tmhc/carpagertask]
      - [0x58918, asm, tmhc/carscript]
      - [0x589e8, asm, tmhc/carhudsound]
      - [0x58d60, asm, tmhc/foddercarsound]
      - [0x59160, asm, tmhc/carweapanimsound]
      - [0x595b0, asm, tmhc/carsound]
      - [0x5c628, asm, tmhc/cartargeting]
      - [0x5c9a0, asm, tmhc/carweap]
      - [0x5dad8, asm, tmhc/carweapbay]
      - [0x5dce8, asm, tmhc/carweapset]
      - [0x5e958, asm, tmhc/carmachineguns]
      - [0x5f3e0, asm, tmhc/carmissiles]
      - [0x5f860, asm, tmhc/cargascan]
      - [0x5fde0, asm, tmhc/cardropmine]
      - [0x60180, asm, tmhc/carflak]
      - [0x60c50, asm, tmhc/carenvweap]
      - [0x610b8, asm, tmhc/carfreezemissiles]
      - [0x61410, asm, tmhc/carswarmermissiles]
      - [0x61ce0, asm, tmhc/carweapsound]
      - [0x62458, asm, tmhc/weaponsound]
      - [0x634a0, asm, tmhc/char]
      - [0x65050, asm, tmhc/charanim]
      - [0x65298, asm, tmhc/animlookat]
      - [0x656f0, asm, tmhc/charcamera]
      - [0x66750, asm, tmhc/charcollis]
      - [0x67bb8, asm, tmhc/charcontrol]
      - [0x68b08, asm, tmhc/chardyn]
      - [0x69c78, asm, tmhc/charhud]
      - [0x6cbc0, asm, tmhc/charmode]
      - [0x6d610, asm, tmhc/charpickup]
      - [0x6e498, asm, tmhc/charreset]
      - [0x6f080, asm, tmhc/charstate]
      - [0x6f390, asm, tmhc/charstateidle]
      - [0x6fbe0, asm, tmhc/charstaterun]
      - [0x70bf0, asm, tmhc/charstatejump]
      - [0x717f0, asm, tmhc/charstateclimb]
      - [0x73180, asm, tmhc/charstatedodgeroll]
      - [0x739f8, asm, tmhc/charstateshove]
      - [0x73d30, asm, tmhc/charstatedeath]
      - [0x73fd8, asm, tmhc/charstatepunch]
      - [0x749a8, asm, tmhc/charstatebatswipe]
      - [0x75330, asm, tmhc/charstateblock]
      - [0x75728, asm, tmhc/charstatethrow]
      - [0x75a38, asm, tmhc/charstatepickup]
      - [0x75cf0, asm, tmhc/charstatepickupmiss]
      - [0x75f30, asm, tmhc/charstateknockback]
      - [0x76340, asm, tmhc/charstateledgegrab]
      - [0x77550, asm, tmhc/charstateledgewobble]
      - [0x77c40, asm, tmhc/charstatemantle]
      - [0x78638, asm, tmhc/chartargeting]
      - [0x78988, asm, tmhc/chartweaks]
      - [0x7ab38, asm, tmhc/charcameratweaks]
      - [0x7b0b8, asm, tmhc/charweap] # weap.cpp?
      - [0x7b398, asm, tmhc/charweapset]
      - [0x7b730, asm, tmhc/charmachinegun]
      - [0x7bea8, asm, tmhc/chunkmap] # ChunkMap.cpp
      - [0x7c6f8, asm, tmhc/chunkscript] # ChunkScript.cpp
      - [0x7da78, asm, tmhc/artifact]
      - [0x7ebe8, asm, tmhc/collector] # collector.cpp
      - [0x80880, asm, tmhc/debris] # debris.cpp
      - [0x81ee0, asm, tmhc/destruct] # destruct.cpp
      - [0x846c8, asm, tmhc/dynodebris] # DynODebris.cpp
      - [0x86a80, asm, tmhc/dynointeractive] # DynOInteractive.cpp
      - [0x88688, asm, tmhc/dynpappy] # DynPappy.cpp
      - [0x88990, asm, tmhc/eestrmbuff] # EEStrmBuff.cpp?
      - [0x89518, asm, tmhc/endurancescript] # endurancescript.cpp
      - [0x89e80, asm, tmhc/endurancewinmenu]
      - [0x8a4b0, asm, tmhc/endurancelosemenu]
      - [0x8a960, asm, tmhc/flame] # flame.cpp
      - [0x8af48, asm, tmhc/flash] # flash.cpp
      - [0x8b048, asm, tmhc/flightcamera] # camera.cpp?
      - [0x8bf38, asm, tmhc/foddercar] # foddercar.cpp
      - [0x8f898, asm, tmhc/foddercarmgr] # CarMgr.cpp?
      - [0x90778, asm, tmhc/foddercarptool] # foddercarptool.cpp
      - [0x98548, asm, tmhc/fodderveh] # fodderveh.cpp
      - [0x9bba8, asm, tmhc/foddervehmgr]
      - [0x9c870, asm, tmhc/foddervehptool] # foddervehptool.cpp
      - [0x9ef48, asm, tmhc/game] # game.cpp
      - [0x9fb30, asm, tmhc/gamechunk]
      - [0xa0310, asm, tmhc/gamemodescript] # GameModeScript.cpp
      - [0xa1550, asm, tmhc/gamemodelevelmenu]
      - [0xa1db0, asm, tmhc/gameoptions] # GameOptions.cpp
      - [0xa1fc0, asm, tmhc/gamepersist] # persist.cpp?
      - [0xa2400, asm, tmhc/gameunlocks] # gameunlocks.cpp
      - [0xa2b80, asm, tmhc/gameworld] # GameWorld.cpp
      - [0xa2db0, asm, tmhc/ghettoweap] # ghettoweap.cpp
      - [0xa3cf0, asm, tmhc/hal] # hal.cpp
      - [0xa4d40, asm, tmhc/hattrack]
      - [0xa4e70, asm, tmhc/healthmeter]
      - [0xa5848, asm, tmhc/staminameter]
      - [0xa5bd8, asm, tmhc/healthstand] # healthstand.cpp
      - [0xa6968, asm, tmhc/helicopter] # helicopter.cpp
      - [0xa8aa8, asm, tmhc/heliptool] # heliptool.cpp
      - [0xa9c20, asm, tmhc/hud] # hud.cpp
      - [0xa9fc8, asm, tmhc/ingamemenu]
      - [0xaa150, asm, tmhc/ingamerootmenu]
      - [0xaa3b8, asm, tmhc/widget]
      - [0xab330, asm, tmhc/interactive] # Interactive.cpp
      - [0xac138, asm, tmhc/level]
      - [0xac298, asm, tmhc/destructiblesoundmanager]
      - [0xac388, asm, tmhc/scenterlevelsound]
      - [0xac398, asm, tmhc/gothlevelsound]
      - [0xac3a8, asm, tmhc/dockslevelsound]
      - [0xac3b8, asm, tmhc/softregionsound]
      - [0xac450, asm, tmhc/softregionsoundmanager]
      - [0xac678, asm, tmhc/soundemitter]
      - [0xac6d8, asm, tmhc/soundemittermanager]
      - [0xac8a8, asm, tmhc/levelobjsndmanager]
      - [0xace20, asm, tmhc/animlevelobjectsound]
      - [0xace80, asm, tmhc/pathsoundemittermanager]
      - [0xadaf0, asm, tmhc/listpager] # ListPager.cpp
      - [0xae290, asm, tmhc/mcmenus] # McMenus.cpp
      - [0xb2060, asm, tmhc/mcpersist] # McPersist.cpp
      - [0xb3488, asm, tmhc/menufactory] # MenuFactory.cpp

      - [0xb3be0, asm, tmhc/missions]
      - [0xb3d40, asm, tmhc/missionasylum]
      - [0xb5700, asm, tmhc/missionbase]
      - [0xb5758, asm, tmhc/missionchasethemole]
      - [0xb5f50, asm, tmhc/missiondowntowncopbattle]
      - [0xb6528, asm, tmhc/missionfindstveh]
      - [0xb6de8, asm, tmhc/missionimpoundlot]
      - [0xb76b8, asm, tmhc/missionmall]
      - [0xb7d50, asm, tmhc/missionscentercombat]

      - [0xb8328, asm, tmhc/modelcam] # ModelCam.cpp
      - [0xb8df0, asm, tmhc/mrgrimmspecialweap]
      - [0xb9588, asm, tmhc/mrslamspecialweap]
      - [0xbb750, asm, tmhc/netcodes] # netCodes.cpp
      - [0xc3ca0, asm, tmhc/netoptions] # NetOptions.cpp
      - [0xc40a8, asm, tmhc/netscore] # NetScore.cpp
      - [0xc5828, asm, tmhc/netstats] # NetStats.cpp
      - [0xc7b88, asm, tmhc/weaponsbitfield]
      - [0xc7cb0, asm, tmhc/nettm] # netTM.cpp
      - [0xcc560, asm, tmhc/npchar] # npchar.cpp
      - [0xcc870, asm, tmhc/onlineingamemenu] # OnlineInGameMenu.cpp
      - [0xd17c8, asm, tmhc/oneplayergamemode]
      - [0xd20d8, asm, tmhc/oneplayerchallengescript]
      - [0xd24b0, asm, tmhc/oneplayerchallengewinmenu]
      - [0xd2850, asm, tmhc/oneplayerchallengelosemenu]
      - [0xd2bf0, asm, tmhc/oneplayermissionscript] # OnePlayerMissionScript.cpp
      - [0xd3d00, asm, tmhc/oneplayerstoryscript] # OnePlayerStoryScript.cpp
      - [0xd4c18, asm, tmhc/onlinegamemode] # OnlineGameMode.cpp
      - [0xd8d98, asm, tmhc/onlinemenus] # OnlineMenus.cpp
      - [0xd9048, asm, tmhc/outlawspecialweap]
      - [0xd9ff8, asm, tmhc/pagertrigger]
      - [0xda208, asm, tmhc/pappytarget]

      - [0xda698, asm, tmhc/pathtool] # pathtool.cpp
      - [0xdc740, asm, tmhc/pausemenu]
      - [0xdcb28, asm, tmhc/pickupptool] # pickupPTool.cpp
      - [0xe0190, asm, tmhc/player] # Player.cpp
      - [0xe0560, asm, tmhc/pointsteering]
      - [0xe2c98, asm, tmhc/positioninfo]
      - [0xe2e80, asm, tmhc/preacherspecialweap]
      - [0xe3520, asm, tmhc/ptool] # ptool.cpp
      - [0xe77d8, asm, tmhc/rbinteract] # RbInteract.cpp
      - [0xe92f8, asm, tmhc/relic] # relic.cpp
      - [0xec0b0, asm, tmhc/reset] # resetcom.cpp?
      - [0xec190, asm, tmhc/projectedrectile]
      - [0xec808, asm, tmhc/roadkillspecialweap]
      - [0xed050, asm, tmhc/rt] # rt.cpp
      - [0xee258, asm, tmhc/rtfade] # RtFade.cpp
      - [0xee658, asm, tmhc/scenterenvweap] # scenterweap.cpp
      - [0xefe58, asm, tmhc/semispecialweap]
      - [0xf05a8, asm, tmhc/main]
      - [0xf08f0, asm, tmhc/shell] # shell.cpp
      - [0xf2780, asm, tmhc/skatgame] # SKATgame.cpp
      - [0xf3c60, asm, tmhc/sound] # sound.cpp
      - [0xf6160, asm, tmhc/soundchan] # soundChan.cpp
      - [0xf75d0, asm, tmhc/soundmgr] # SoundMgr.cpp
      - [0xf9470, asm, tmhc/soundptool] # soundptool.cpp
      - [0xfa790, asm, tmhc/spectrespecialweap]
      - [0xfae18, cpp, tmhc/Strings] # Strings.cpp... some weird code here
      - [0xfae80, asm, tmhc/musictrack]
      - [0xfb4b0, asm, tmhc/strmsound] # strmSound.cpp
      - [0xfbd00, asm, tmhc/sweettoothspecialweap]
      - [0xfc598, asm, tmhc/thumperspecialweap]
      - [0xfd2a8, asm, tmhc/timberdebris] # timberdebris.cpp
      - [0xfe638, asm, tmhc/tilepager] # TilePager.cpp
      - [0x100100, asm, tmhc/tmslink] # TMSlink.cpp
      - [0x1007d0, asm, tmhc/transitionloader] # TransitionLoader.cpp
      - [0x100b50, asm, tmhc/transzonescript]
      - [0x100be0, asm, tmhc/twoplayerdeathscript]
      - [0x100f18, asm, tmhc/twoplayerdeathmenu]
      - [0x1015b0, asm, tmhc/twoplayergamemode]
      - [0x101db0, asm, tmhc/ui] # Ui.cpp
      - [0x103138, asm, tmhc/uicarpager] # UiCarPager.cpp
      - [0x1038a0, asm, tmhc/uicarscript]
      - [0x103cd0, asm, tmhc/uicustomcontrolmenu] # UiCustomControlMenu.cpp
      - [0x1048e8, asm, tmhc/uiiconanimmgr]
      - [0x104c68, asm, tmhc/uidnas_eula]
      - [0x105408, asm, tmhc/uimpdnasmenu]
      - [0x105ce0, asm, tmhc/uiinternetlobbymenu]
      - [0x10d480, asm, tmhc/uiloadscreen]
      - [0x10d800, asm, tmhc/uiloadgamemenu] # UiLoadGameMenu.cpp
      - [0x10e238, asm, tmhc/storyinfoblock]
      - [0x10e520, asm, tmhc/uioverwritegamemenu]
      - [0x10e750, asm, tmhc/uiwhichgamemenu]
      - [0x10eba8, asm, tmhc/uisplashmenu]
      - [0x10ed38, asm, tmhc/uiexitmenu]
      - [0x10ee10, asm, tmhc/uimainmenu]
      - [0x10f1d0, asm, tmhc/quitgamemenu]
      - [0x10f3e8, asm, tmhc/uisingleplayermenu]
      - [0x10f6c0, asm, tmhc/uicarselectmenu]
      - [0x10fb88, asm, tmhc/uilevelselectmenu]
      - [0x10fee0, asm, tmhc/uimissionselectmenu]
      - [0x1103a0, asm, tmhc/uisplitscreenmenu]
      - [0x110930, asm, tmhc/uienemyselectmenu]
      - [0x110d70, asm, tmhc/uinetworkinitializationscreen]
      - [0x112998, asm, tmhc/uiselectnetworkconfigurationscreen]
      - [0x113270, asm, tmhc/uimpplayernetsetmenu]
      - [0x114380, asm, tmhc/uinetworkinitializationstatusscreen]
      - [0x1151c8, asm, tmhc/uimplanlogonmenu]
      - [0x116098, asm, tmhc/uimplogonmenu]
      - [0x117020, asm, tmhc/uimplogonstatusscreen]
      - [0x118f10, asm, tmhc/uimpgamename]
      - [0x11a6f0, asm, tmhc/uimpjoingamepasswordscreen]
      - [0x11b160, asm, tmhc/uimpjoingamestatusscreen]
      - [0x11d960, asm, tmhc/uinetlogoutscreen]
      - [0x11e378, asm, tmhc/uimpinternetlobbyselectionmenu]
      - [0x121360, asm, tmhc/uimpinternetlobbyselectionwaiting]
      - [0x1231f8, asm, tmhc/uileavegamemenu]
      - [0x1239a0, asm, tmhc/uimpinternetmenu]
      - [0x1264c0, asm, tmhc/uimponlinemenu]
      - [0x126ff8, asm, tmhc/uiselectuniversescreen]
      - [0x1282a0, asm, tmhc/uisprebootiopscreen]
      - [0x129120, asm, tmhc/uimpannouncementsmenu]
      - [0x129b70, asm, tmhc/uineterrormenu]
      - [0x12c628, asm, tmhc/uioptionsmenu]
      - [0x12d140, asm, tmhc/uiscript]
      - [0x12dab8, asm, tmhc/uitransitions]
      - [0x12db70, asm, tmhc/uimpusagepolicymenu]
      - [0x12ec98, asm, tmhc/uiwaitingroommenu] # UiWaitingRoomMenu.cpp
      - [0x13af78, asm, tmhc/pspui] # Interesting...
      - [0x13b588, asm, tmhc/weap] # weap.cpp
      - [0x1421f0, asm, tmhc/weaptweaks]
      - [0x142e88, asm, tmhc/worldloader] # WorldLoader.cpp
      - [0x143428, asm, tmhc/zoneloader] # ZoneLoader.cpp
      - [0x143850, asm, tmhc/zonescript]
      - [0x144c68, asm, sdk/libgcc2]

      - [0x299c10, databin] # .vutext
      - [0x2a6d00, databin] # .data
      - [0x2c8e00, databin] # .rodata
      - [0x32bf00, databin] # .gcc_except_table
      - [0x32c080, databin] # .sdata
      # - [0xb54, sbss] # .sbss
      - [0x32f6d4, databin] # .reginfo
      - [0x3330b4, databin] # .DVP.overlay
      - [0x338aec, databin] # .debug_str
      - [0x339b38, databin] # .stab
      - [0x353644, databin] # .stabstr
      - [0x353774, databin] # .mdebug
      - [0x3fbcf8, databin] # .bss
      - [0x445360, databin] # .symtab
      - [0x48c420, databin] # .strtab
      - [0x4f670b, databin] # .shstrtab
  - [0x4f71b4]
